#!/usr/bin/env bash

set -e

set -vx
(cd charts/prometheus-process-exporter; helm package .)
cr upload -o opvizor -r prometheus-process-exporter -t $GITHUB_TOKEN -p charts/prometheus-process-exporter
cr index -o opvizor -r prometheus-process-exporter -t $GITHUB_TOKEN -p docs/index.yaml
git add docs/index.yaml
git commit -m 'Update the helm chart repository index'
git push origin master
